### ISSUE TITLE
Declarar funciones

### ISSUE THREAD

**Issue by JimenaEB** [jagtrrz/excuses-generator#1]
Ojo al declarar las funciones el nombre y el paréntesis van siempre juntos 'function name(param1, param2){ //code; }'
https://github.com/jagtrrz/excuses-generator/blob/8e1a680c8bf301598cf27aee10a23932faff503a/index.js#L14

**Comment by jagtrrz** [comment]
Vale, apuntado para que no me vuelva a pasar. 
He subido otra vez el repo sin el espacio y he aprovechado para quitar una linea más de código que me parece que sobraba. 
![imagen](https://user-images.githubusercontent.com/75372070/105380003-b96a1700-5c0d-11eb-918a-223eb9cad636.png)

**Comment by JimenaEB** [comment]
Perfecto!
